# Generated by Django 4.0.5 on 2022-06-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_funcionario_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('feature', models.CharField(max_length=100, verbose_name='Features')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descricao')),
                ('icone', models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-laptop-phone', 'Responsivo'), ('lni-layers', 'Design'), ('lni-leaf', 'Moderno'), ('lni-rocket', 'Foguete')], max_length=16, verbose_name='Icone')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
    ]
